spring:
  profiles:
    include: secret
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
server:
  servlet:
    context-path: /api
logging:
  level:
    org.hibernate.SQL: debug

springdoc:
  api-docs:
    enabled: true
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    display-request-duration: true  # ?? ?? ?? ?? ??
    doc-expansion: list  # Swagger UI?? API ??? ?? ?? ?? (none: ??, list: ??, full: ?? ??)
    persistAuthorization: true  # ??? ???? ??? Authorization ?? ?? ??\
